### PR TITLE
fix: cannot build on modern kernel - Drop decnet 

### PR DESCRIPTION
**Pull request by buzzdan**
this is a cherry-pick from upstream for commit that fixed a missing header from kernel.
original PR:
https://github.com/kernelslacker/trinity/pull/41

the issue:
Drop decnet as it has been removed since kernel 6.1 and https://github.com/torvalds/linux/commit/1202cdd665315c525b5237e96e0bedc76d7e754f resulting in the following build failure:

net/proto-decnet.c:5:10: fatal error: linux/dn.h: No such file or directory
5 | #include <linux/dn.h>
| ^~~~~~~~~~~~
Fixes:

http://autobuild.buildroot.org/results/47e0a5e0b6fcf33ab4f9848d5d8c2be9e5283950

### CODE REVIEW

**Comment by tigrawap** [comment]
if it compiles, that's fine
but on wekapp side - make sure only problematic OSes  use this one. by pointing ALL oses to new version they might got broken

**Comment by buzzdan** [comment]
> if it compiles, that's fine but on wekapp side - make sure only problematic OSes use this one. by pointing ALL oses to new version they might got broken

@tigrawap 
yes we have this mechanism already, once merged, i will use commit number in our code:

```python
    class OsesWithBump(OuterClassOSOverride):
        oses = [Rocky9, Ubuntu20, Ubuntu22]
        version = '77030c10bcaaa02a9d7527ab4a37b48550c45695'
```

**Comment by tigrawap** [comment]
Please have override only what what you are building right now
Otherwise you have to recreate all images across all environments. As compiling new trinity will add time to everyone

**Comment by buzzdan** [comment]
@tigrawap im building ubuntu20, im not sure ubuntu22 will work as well
i will look into it

**Comment by buzzdan** [comment]
this patch will work for:
ubuntu20
ubuntu20noofed
ubuntu22 (kernel 5.15)

doesnt work for:
rocky 9 (kernel 5.14)

**Review by tigrawap — APPROVED** [review]

**Pull request merged**
